version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/acher0nparth/CEN3031Project/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  db-test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # pytest -v

workflows:
  my-custom-workflow:
    jobs:
      - db-test